# Generated by Django 3.1.2 on 2020-10-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0004_auto_20201027_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
