# Generated by Django 3.1.2 on 2020-10-28 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0005_auto_20201027_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='type',
            new_name='kind',
        ),
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='myauth.user'),
        ),
    ]
